# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-23 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0034_subadv'),
        ('strategy', '0002_auto_20190523_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyAdvisorID', to='blog.FitAdvisors')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors_strategy', to='strategy.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyMgrName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MgrName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyMgrName', to='blog.FitManagerNames')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgrnames_strategy', to='strategy.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyMSCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyMSCat', to='blog.FitCategorys')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mscats_strategy', to='strategy.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyMSSubAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSubAdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategyMSSubAdv', to='blog.FitSubAdvisors')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mssubadvs_strategy', to='strategy.Strategy')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='advisors',
            field=models.ManyToManyField(through='strategy.StrategyAdvisor', to='blog.FitAdvisors'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='mgrnames',
            field=models.ManyToManyField(through='strategy.StrategyMgrName', to='blog.FitManagerNames'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='mscats',
            field=models.ManyToManyField(through='strategy.StrategyMSCat', to='blog.FitCategorys'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='mssubadvs',
            field=models.ManyToManyField(through='strategy.StrategyMSSubAdv', to='blog.FitSubAdvisors'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='strategy',
            unique_together=set([('user', 'name')]),
        ),
    ]
