# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181215_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
