# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181219_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('MSCatID', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
