# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_mscat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('MSCatID', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='MSCatDbId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.MSCats'),
        ),
    ]
