# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_shares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shares',
        ),
    ]
