# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_funds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funds',
        ),
    ]
