# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_fitadvisors_fitcategorys_fitmanagernames_fitsubadvisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitdefault',
            name='AdvisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitAdvisors'),
        ),
        migrations.AddField(
            model_name='fitdefault',
            name='CategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitCategorys'),
        ),
        migrations.AddField(
            model_name='fitdefault',
            name='ManagerNameId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitManagerNames'),
        ),
        migrations.AddField(
            model_name='fitdefault',
            name='SubAdvisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitSubAdvisors'),
        ),
    ]
