# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-26 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_fitdefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitdefault',
            name='AdvisorId',
        ),
        migrations.RemoveField(
            model_name='fitdefault',
            name='CategoryId',
        ),
        migrations.RemoveField(
            model_name='fitdefault',
            name='ManagerNameId',
        ),
        migrations.RemoveField(
            model_name='fitdefault',
            name='SubAdvisorId',
        ),
        migrations.DeleteModel(
            name='FitDefault',
        ),
    ]
