# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-26 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20190426_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Category', models.CharField(max_length=50, null=True)),
                ('MFVA', models.CharField(max_length=5, null=True)),
                ('SubAdvised', models.CharField(max_length=3, null=True)),
                ('IndexFund', models.CharField(max_length=3, null=True)),
                ('WatchList', models.CharField(max_length=3, null=True)),
                ('VIT', models.CharField(max_length=3, null=True)),
                ('FundOfFunds', models.CharField(max_length=3, null=True)),
                ('InceptionDate', models.DateField(null=True)),
                ('Advisor', models.CharField(max_length=200, null=True)),
                ('SubAdvisor', models.CharField(max_length=200, null=True)),
                ('AUM', models.DecimalField(decimal_places=16, max_digits=24, null=True)),
                ('NFYTD', models.DecimalField(decimal_places=22, max_digits=36, null=True)),
                ('NF2017', models.DecimalField(decimal_places=22, max_digits=36, null=True)),
                ('NF2016', models.DecimalField(decimal_places=22, max_digits=36, null=True)),
                ('TR_YTD', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('TR_1Y', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('TR_2Y', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('TR_3Y', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('TR_5Y', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('TR_10Y', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('SubStart', models.CharField(max_length=200, null=True)),
                ('SubSched', models.CharField(max_length=200, null=True)),
                ('SubAdvEffRate', models.DecimalField(decimal_places=22, max_digits=30, null=True)),
                ('SubRate', models.DecimalField(decimal_places=11, max_digits=21, null=True)),
                ('Alpha', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('ExcessRet', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('Sharpe', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('InfoRat', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('Beta', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('Stdev', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('R2', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('UpsideCap', models.DecimalField(decimal_places=11, max_digits=21, null=True)),
                ('DownsideCap', models.DecimalField(decimal_places=11, max_digits=21, null=True)),
                ('TrackingErr', models.DecimalField(decimal_places=15, max_digits=21, null=True)),
                ('QRK_YTD', models.IntegerField(null=True)),
                ('QRK_1Y', models.IntegerField(null=True)),
                ('QRK_2Y', models.IntegerField(null=True)),
                ('QRK_3Y', models.IntegerField(null=True)),
                ('QRK_5Y', models.IntegerField(null=True)),
                ('QRK_10Y', models.IntegerField(null=True)),
                ('QRK_15Y', models.IntegerField(null=True)),
                ('QRK_Alpha', models.IntegerField(null=True)),
                ('QRK_ExcessRet', models.IntegerField(null=True)),
                ('QRK_Sharpe', models.IntegerField(null=True)),
                ('QRK_InfoRat', models.IntegerField(null=True)),
                ('QRK_Beta', models.IntegerField(null=True)),
                ('QRK_Stdev', models.IntegerField(null=True)),
                ('QRK_R2', models.IntegerField(null=True)),
                ('QRK_UpsideCap', models.IntegerField(null=True)),
                ('QRK_DownsideCap', models.IntegerField(null=True)),
                ('QRK_TrackingErr', models.IntegerField(null=True)),
                ('TeamManaged', models.CharField(max_length=3, null=True)),
                ('ProspectusNetExpenseRatio', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('ManagerName', models.CharField(max_length=1500, null=True)),
                ('ManagerTenureLongest', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('ManagerTenureAverage', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('Benchmark', models.CharField(max_length=200, null=True)),
                ('SecId', models.CharField(max_length=10, null=True)),
                ('FundId', models.CharField(max_length=10, null=True)),
                ('AdvisorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitAdvisors')),
                ('CategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitCategorys')),
                ('ManagerNameId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitManagerNames')),
                ('SubAdvisorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.FitSubAdvisors')),
            ],
        ),
    ]
