# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Advisors(models.Model):  # model name must NOT the same as column name!
	Name = models.CharField(max_length=400,null=False)

class MSCats(models.Model):  # model name must NOT the same as column name!
	Name = models.CharField(max_length=50,null=False)

class MSSubAdvs(models.Model):  # model name must NOT the same as column name!
	Name = models.CharField(max_length=730,null=False)

class Company(models.Model):
	Name	= models.CharField(max_length=40)
	CUSIP	= models.CharField(max_length=9,null=True)
	SecId	= models.CharField(max_length=10,null=True)
	FundId	= models.CharField(max_length=10,null=True)
	MRFundID	= models.CharField(max_length=15,null=True)
	PerfID	= models.CharField(max_length=15,null=True)
	Ticker	= models.CharField(max_length=12,null=True)
	OldestSh	= models.CharField(max_length=5,null=True)
	Advisor	= models.CharField(max_length=200,null=True)
	AdvisorID = models.ForeignKey(Advisors, on_delete=models.SET_NULL, null=True)
	FirmName	= models.CharField(max_length=100,null=True)
	BrndName	= models.CharField(max_length=44,null=True)
	BrndNmID	= models.CharField(max_length=10,null=True)
	InceptDt	=models.DateField(null=True)			
	GlBrdGrp	= models.CharField(max_length=13,null=True)
	GlBrdCat	= models.CharField(max_length=39,null=True)
	USCatGrp	= models.CharField(max_length=20,null=True)
	MSCat	= models.CharField(max_length=50,null=True)
	MSCatDbId = models.ForeignKey(MSCats, on_delete=models.SET_NULL, null=True)
	MSCatID	= models.CharField(max_length=10,null=True)
	MSCatStr	=models.DateField(null=True)			
	MSInsCat	= models.CharField(max_length=43,null=True)
	MSRatAll	= models.CharField(max_length=2,null=True)
	MSRat3Y	= models.CharField(max_length=2,null=True)
	MSRat5Y	= models.CharField(max_length=2,null=True)
	MSRat10Y	= models.CharField(max_length=2,null=True)
	EqStyleL	= models.CharField(max_length=12,null=True)
	EqStyleS	= models.CharField(max_length=12,null=True)
	FxStyleL	= models.CharField(max_length=16,null=True)
	MSSubAdv	= models.CharField(max_length=721,null=True)
	MSSubAdvId = models.ForeignKey(MSSubAdvs, on_delete=models.SET_NULL, null=True)
	MSSubFee	= models.CharField(max_length=516,null=True)
	TeamMgd	= models.CharField(max_length=3,null=True)
	MgrHist	= models.CharField(max_length=5000,null=True)
	MgrName	= models.CharField(max_length=1000,null=True)
	MgrTnrAv	=models.DecimalField(max_digits=6,decimal_places=2, null=True)
	MgrTnrLg	=models.DecimalField(max_digits=6,decimal_places=2, null=True)
	PPBnch	= models.CharField(max_length=400,null=True)
	PPBnchID	= models.CharField(max_length=10,null=True)
	PPBIncpt	=models.DateField(null=True)			
	SPBench	= models.CharField(max_length=400,null=True)
	AUMShr	= models.BigIntegerField(null=True)			
	AUMShrDt	=models.DateField(null=True)			
	FSizeCur	= models.BigIntegerField(null=True)			
	FSizeDt	=models.DateField(null=True)			
	hldBondL	=models.IntegerField(null=True)			
	hldBondS	=models.IntegerField(null=True)			
	hldLong	=models.IntegerField(null=True)			
	hldOthrL	=models.IntegerField(null=True)			
	hldOthrS	=models.IntegerField(null=True)			
	hldStckL	=models.IntegerField(null=True)			
	hldStckS	=models.IntegerField(null=True)			
	hldT10	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	hldofInv	= models.CharField(max_length=3,null=True)
	hldAT10	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	hldAT10D	=models.DateField(null=True)			
	Yld12M	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	Yld12MD	=models.DateField(null=True)			
	SECYld	=models.DecimalField(max_digits=10,decimal_places=5,null=True)
	SECYldD	=models.DateField(null=True)			
	DivdCur	=models.DecimalField(max_digits=11,decimal_places=7,null=True)
	DivdCurD	=models.DateField(null=True)			
	DivdNAVC	=models.DecimalField(max_digits=8,decimal_places=4,null=True)
	PortDate	=models.DateField(null=True)			
	VirtClss	= models.CharField(max_length=3,null=True)
	FeeMgt	=models.DecimalField(max_digits=10,decimal_places=3,null=True)
	NExpSAR	=models.DecimalField(max_digits=7,decimal_places=3,null=True)
	NExpSARD	=models.DateField(null=True)			
	ChrgAR	=models.DecimalField(max_digits=6,decimal_places=3,null=True)
	ChrgARD	=models.DateField(null=True)			
	NExpPrs	=models.DecimalField(max_digits=7,decimal_places=3,null=True)
	NExpPrsD	=models.DecimalField(max_digits=7,decimal_places=3,null=True)
	ObjPros	= models.CharField(max_length=30,null=True)
	Fee12b1	=models.DecimalField(max_digits=5,decimal_places=3,null=True)
	TurnRat	=models.DecimalField(max_digits=10,decimal_places=3,null=True)
	TurnRatD	=models.DateField(null=True)			
	CashN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AABondN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AACashN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AAEqN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AANUSBdN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AANUSEqN	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	AAOthrN	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	AAUSBdN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AAUSEqN	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	AAABN	=models.DecimalField(max_digits=8,decimal_places=6,null=True)
	AABondL	=models.DecimalField(max_digits=15,decimal_places=6,null=True)
	AACashL	=models.DecimalField(max_digits=16,decimal_places=6,null=True)
	AAEqL	=models.DecimalField(max_digits=15,decimal_places=6,null=True)
	AANUSBdL	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	AANUSEqL	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	AAOthrL	=models.DecimalField(max_digits=15,decimal_places=6,null=True)
	AAUSBdL	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	AAUSEqL	=models.DecimalField(max_digits=10,decimal_places=6,null=True)
	FoFIH	= models.CharField(max_length=3,null=True)
	Leveragd	= models.CharField(max_length=3,null=True)
	FeederFd	= models.CharField(max_length=3,null=True)
	MasterFd	= models.CharField(max_length=3,null=True)
	MasterN	= models.CharField(max_length=50,null=True)
	MSTRFundID	= models.CharField(max_length=10,null=True)
	Sharia	= models.CharField(max_length=3,null=True)
	Ethical	= models.CharField(max_length=19,null=True)
	ModelFd	= models.CharField(max_length=2,null=True)
	Avail529	= models.CharField(max_length=3,null=True)
	AvailRet	= models.CharField(max_length=3,null=True)
	AvailIns	= models.CharField(max_length=3,null=True)
	TaxMgd	= models.CharField(max_length=3,null=True)
	Contrarn	= models.CharField(max_length=3,null=True)
	BrkAvail	= models.CharField(max_length=4000,null=True)
	EnhIndex	= models.CharField(max_length=3,null=True)
	Indexed	= models.CharField(max_length=3,null=True)
	FoF	= models.CharField(max_length=3,null=True)
	SocCons	= models.CharField(max_length=3,null=True)
	NonDiv	= models.CharField(max_length=3,null=True)
	ClsdAll	= models.CharField(max_length=3,null=True)
	ClsdALLD	=models.DateField(null=True)			
	ClsdNew	= models.CharField(max_length=3,null=True)
	ClsdNewD	=models.DateField(null=True)			
	FeeAccnt	=models.DecimalField(max_digits=13,decimal_places=6,null=True)
	FeeAdmin	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeAdv	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeAudit	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeCust	=models.DecimalField(max_digits=13,decimal_places=6,null=True)
	FeeDistr	=models.DecimalField(max_digits=13,decimal_places=6,null=True)
	FeeIns	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeLegal	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeOrg	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeOthr	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeePerf	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeProf	=models.DecimalField(max_digits=12,decimal_places=6,null=True)
	FeeReg	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	FeeShRpt	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	FeeTA	=models.DecimalField(max_digits=11,decimal_places=6,null=True)
	Domicile	= models.CharField(max_length=15,null=True)
	BaseCurr	= models.CharField(max_length=20,null=True)
	ObsoltD	=models.DateField(null=True)			
	ObsoltTy	= models.CharField(max_length=30,null=True)
	DiscCurr	=models.DecimalField(max_digits=9,decimal_places=6,null=True)
	ShrType	= models.CharField(max_length=15,null=True)
	AABdLR	= models.CharField(max_length=20,null=True)
	AABdL	= models.CharField(max_length=20,null=True)
	AACshLR	= models.CharField(max_length=20,null=True)
	AACBLR	= models.CharField(max_length=20,null=True)
	AAEqLR	= models.CharField(max_length=20,null=True)
	AAxUSBLR	= models.CharField(max_length=20,null=True)
	AAxUSELR	= models.CharField(max_length=20,null=True)
	AAOtLR	= models.CharField(max_length=20,null=True)
	AAPSLR	= models.CharField(max_length=20,null=True)
	AAUSBLR	= models.CharField(max_length=20,null=True)
	AAUSELR	= models.CharField(max_length=20,null=True)

	def __str__(self):
		return self.Name

	# def get_column_names(self):
	# 	return ["Name", "CUSIP", "SecId", "FundId", "Master FundId", "PerformanceId", "Ticker", "Oldest Share Class", "Advisor", "Firm Name", "Branding Name", "Branding Name ID", "Inception Date", "Global Broad Category Group", "Global Category", "US Category Group", "Morningstar Category", "Morningstar Category Id", "Morningstar Category Start Date", "Morningstar Institutional Category", "Morningstar Rating Overall", "Morningstar Rating 3 Yr", "Morningstar Rating 5 Yr", "Morningstar Rating 10 Yr", "Equity Style Box (Long)", "Equity Style Box (Short)", "Fixed Inc Style Box (Long)", "Subadvisor", "Subadvisor Fee Ratio", "Team Managed", "Manager History", "Manager Name", "Manager Tenure (Average)", "Manager Tenure (Longest)", "Primary Prospectus Benchmark", "Primary Prospectus Benchmark Id", "Primary Prospectus Benchmark Inception Date", "Secondary Prospectus Benchmark", "Net Assets - Share Class Base Currency", "Net Assets Date", "Fund Size Base Currency", "Fund Size Date", "# of Bond Holdings (Long)", "# of Bond Holdings (Short)", "# of Holdings (Long)", "# of Other Holdings (Long)", "# of Other Holdings (Short)", "# of Stock Holdings (Long)", "# of Stock Holdings (Short)", "% Asset in Top 10 Holdings", "Holding of an Investment", "Latest % Asset in Top 10 Holdings", "Latest % Asset in Top 10 Holdings Date", "12 Mo Yield", "12 Mo Yield Date", "SEC Yield", "SEC Yield Date", "Latest Dividend Base Currency", "Latest Dividend Date", "Latest Dividend NAV Base Currency", "Portfolio Date", "Virtual Class", "Management Fee", "Semi-Annual Report Net Expense Ratio", "Semi-Annual Report Net Expense Ratio Date", "Annual Report Ongoing Charge", "Annual Report Ongoing Charge Date", "Prospectus Net Expense Ratio", "Prospectus Gross Expense Ratio", "Prospectus Objective", "12b-1 Fee", "Turnover Ratio %", "Turnover Ratio % Date", "Cash % (Net)", "Asset Alloc Bond % (Net)", "Asset Alloc Cash % (Net)", "Asset Alloc Equity % (Net)", "Asset Alloc Non-US Bond % (Net)", "Asset Alloc Non-US Equity % (Net)", "Asset Alloc Other % (Net)", "Asset Alloc US Bond % (Net)", "Asset Alloc US Equity % (Net)", "Asset Backed % (Net)", "Asset Alloc Bond % (Long)", "Asset Alloc Cash % (Long)", "Asset Alloc Equity % (Long)", "Asset Alloc Non-US Bond % (Long)", "Asset Alloc Non-US Equity % (Long)", "Asset Alloc Other % (Long)", "Asset Alloc US Bond % (Long)", "Asset Alloc US Equity % (Long)", "In-House FOF", "Leveraged Fund", "Feeder Fund", "Master Fund", "Master Fund Name", "Master FundId", "Sharia Compliant", "Ethical Issue Strategy Focus", "Model Portfolio Fund", "Available For 529 Only", "Available For Retirement Plan", "Available In Insurance Product", "Tax Managed", "Contrarian", "Brokerage Availability", "Enhanced Index", "Index Fund", "Fund of Funds", "Socially Conscious", "Non Diversified", "Closed to All Inv", "Closed to All Investors Date", "Closed to New Inv", "Closed to New Investors Date", "Accounting Fee", "Administrator Fee", "Advisor Fee", "Auditor Fee", "Custodian Fee", "Distribution Fee", "Insurance Fee", "Legal Fee", "Organization Fee", "Other Fee", "Performance Fee", "Professional Fee", "Registration Fee", "Shareholder Reporting Fee", "Transfer Agency Fee", "Domicile", "Base Currency", "Obsolete Date", "Obsolete Type", "Discount (Current)", "Share Class Type", "Asset Alloc Bond % (Long Rescaled)", "Asset Alloc Bond % (Long)", "Asset Alloc Cash % (Long Rescaled)", "Asset Alloc Conv Bond % (Long Rescaled)", "Asset Alloc Equity % (Long Rescaled)", "Asset Alloc Non-US Bond % (Long Rescaled)", "Asset Alloc Non-US Equity % (Long Rescaled)", "Asset Alloc Other % (Long Rescaled)", "Asset Alloc Pref Stock % (Long Rescaled)", "Asset Alloc US Bond % (Long Rescaled)", "Asset Alloc US Equity % (Long Rescaled)"]


